fix: remove one unnecessary signature when generated encrypted nvm key
nevermined-io/sdk-js pull request #698
Opened 2024-07-31 14:43 UTC by aaitor

## Description

Add a description of your changes here.

## Is this PR related with an open issue?

Related to Issue #

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] Follows the code style of this project.
- [ ] Tests Cover Changes
- [ ] Documentation

#### Funny gif

![Put a link of a funny gif inside the parenthesis-->]()

2024-07-31 14:44 UTC, metabacalhau approved these changes

2024-07-31 14:47 UTC, eruizgar91 requested changes

2024-07-31 15:01 UTC, aaitor commented on src/models/NvmApiKey.ts
> -    const nvmApiKey = await this.generate(
removed

2024-08-01 07:12 UTC, eruizgar91 approved these changes

2024-08-01 07:12 UTC, merged